### ISSUE TITLE
Server cannot get host entry from local address when bound to IPAddress.Any

### ISSUE THREAD

**Issue by suppergerrie2** [neuralm/Neuralm-Server#28]
When changing [IPAddress.Loopback](https://github.com/neuralm/Neuralm-Server/blob/ac56df06a43042aec0d455d138cc6b3d187731d6/src/Neuralm.Presentation.CLI/Program.cs#L80) to IPAddress.Any and connecting to the server from another device in the local network the connection crashes because the hostentry cannot be found in [TcpNetworkConnector](https://github.com/neuralm/Neuralm-Server/blob/ac56df06a43042aec0d455d138cc6b3d187731d6/src/Neuralm.Infrastructure/Networking/TcpNetworkConnector.cs#L50)

**Comment by metalglove** [comment]
We do not check for the IPEndpoint anymore.
